# Generated by Django 5.1.1 on 2025-05-24 17:15

import Main.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('scientific_name', models.CharField(max_length=255, verbose_name='Nombre Científico')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=Main.models.Fish.get_media_path_fish, verbose_name='Imagen del Pez')),
            ],
            options={
                'verbose_name': 'Pez',
                'verbose_name_plural': 'Peces',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('photo', models.ImageField(upload_to=Main.models.User.get_media_path, verbose_name='Foto del Usuario')),
                ('banner', models.ImageField(upload_to=Main.models.User.get_media_path, verbose_name='Foto banner')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='UserFish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured', models.BooleanField(default=False, verbose_name='Capturado')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=Main.models.UserFish.get_media_path_userfish, verbose_name='Foto del pez más bonito')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.fish', verbose_name='Pez')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Relación Usuario-Pez',
                'verbose_name_plural': 'Relaciones Usuario-Pez',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='fishes',
            field=models.ManyToManyField(related_name='users', through='Main.UserFish', to='Main.fish', verbose_name='Peces Capturados'),
        ),
    ]
